
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 11 22:01:33 CLT 2014
//----------------------------------------------------

package aSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESTA = 4;
  public static final int NUMERO = 2;
  public static final int NUEVALINEA = 7;
  public static final int MULT = 5;
  public static final int error = 1;
  public static final int SUMA = 3;
  public static final int DIVISION = 6;
  public static final int EOF = 0;
}

